id: I442B1CF0
legacy_id: P004525
ocr_import_info:
  bdrc_scan_id: W10347
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T12:29:14'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T14:16:30.612734+00:00'
last_modified: 2022-08-30 22:22:30.623567
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W10347
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW10347
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཚུལ་ཁྲིམས་རིན་ཆེན།
  author: ཞུ་ཆེན་ཚུལ་ཁྲིམས་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.6929119276181247
  ocr_word_median_confidence_index: 0.7699999809265137
quality: null
bases:
  I2908:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2908
      total_pages: 603
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I2908.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6103317720635493
    legacy_id: v007
  I2905:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2905
      total_pages: 644
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2905.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.647778022233112
    legacy_id: v004
  I2904:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2904
      total_pages: 584
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2904.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.7015455350103929
    legacy_id: v003
  I2907:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2907
      total_pages: 657
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I2907.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7280922764664692
    legacy_id: v006
  I2906:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2906
      total_pages: 661
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I2906.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.7036077608503194
    legacy_id: v005
  I2902:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2902
      total_pages: 676
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2902.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.7441948857945363
    legacy_id: v001
  I2903:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2903
      total_pages: 637
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2903.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7461172214873694
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
