id: I442B1CF0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:34:03+00:00'
last_modified: '2022-06-08T01:41:57.170951+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W10347
  title: གསུང་འབུམ། ཚུལ་ཁྲིམས་རིན་ཆེན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9C94:
      image_group_id: I2902
      title: ''
      total_pages: 676
      order: 1
      base_file: 9C94.txt
    4D51:
      image_group_id: I2903
      title: ''
      total_pages: 637
      order: 2
      base_file: 4D51.txt
    294F:
      image_group_id: I2904
      title: ''
      total_pages: 584
      order: 3
      base_file: 294F.txt
    3D44:
      image_group_id: I2905
      title: ''
      total_pages: 644
      order: 4
      base_file: 3D44.txt
    F7C5:
      image_group_id: I2906
      title: ''
      total_pages: 661
      order: 5
      base_file: F7C5.txt
    7AEF:
      image_group_id: I2907
      title: ''
      total_pages: 657
      order: 6
      base_file: 7AEF.txt
    B4A4:
      image_group_id: I2908
      title: ''
      total_pages: 603
      order: 7
      base_file: B4A4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
